name: ${name}
version: ${version}
description: ${description}
author: ${author}
website: ${url}
main: ${mainClass}
depend: ${dependencies}
commands:
  tell:
    aliases:
      - msg
      - message
      - pm
      - whisper
      - w
    description: Whisper command.
permissions:
  publicwhispers.publicize:
    description: Makes the users whispers public.
    default: true